version: "3.9"
services:
  service:
    container_name: "torch-gpu_service"
    build:
        context: "."
        dockerfile: "torch-jupyter-gpu.Dockerfile"
    ports:
      - "8888:8888"
    volumes:
      - "./neural_machine_translation:/src/Projects"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
